string = "TCAGGTCTTAAAAGGCTAGACGGATGATCCGTCATGTGCTTATAACCTCATACCGCGTGCGCTCCCTAGTTCTTGTGGGAAGAACCTCCGATCACTTCCGTACTTCAGGTCATTTTCTGTGATAACCTCTTCACCATTAGGTATGCTGTTACGGCTCACTATGTCTTAAGGGTATACAGGGATGGGCCCACTATATACCACTAGCGTGGAACGTCGTTCCACCTAGATACATACACCCTTCAAATTGTGGTCATTCTAAAAAAGGCTTCTTCTGAGACGGTAACTGGCTATGGGTGATCGCTCGTACAGGTATCTCGAAAAGGAGATGGGGCTCATCGTTTGTCAATCCCCCCATCTGAGGCTTTGGGTCACATTGCAGTTTCAGATCCCATCTTCTGTAACCAACCTGCGAACTGCTTCAACGTGCAACTTAGTACTAAGTACGATTGAGCGTAGCCCTAAGGGGTTAACTGTACGCTATGAGTTCATTTCATGTTTGTCTGGGAAATTCGACGTACATACTCCATGTGATGGCTTATAGTCCTCAGCATGGCAAAAACTCGTTACAGAAATAAATTGGCGGGACTACGCCATACTGTTGCCCAGTTATACGCATGGGTAAGCACGCCCAGTTATGTTCCTCACGGTTGATTGCGCGATCCGTTTCGGCCGAATGCCGCGACGGTGGTTGACCCTGTTGACATTTTGTCGTCTGTCTCTAGGCCACTTCGCAAAGACCAGCTCCCCTAAAGACTACATTGCCGTCGGTATCCATCATTCCTGAGAGACGTGAGGCCCCCTTTCGTAACCCAGCCCGGCTGAAATCTCAATTCCTTAACCTCGGCCCTTTCTATATTTATCTAGTCACTCGGTATATGTTAGCTAGGTTATCCACCATAGAAATTGTCAACTTGATGCCAGCCGGCAGGATATAGTAAGGATATCGAAGTCCCAGTATTGACATCAAGACGTCATCCCTTCCGTGGGGGATCTAAAAAC"

'''
Author : Sujit Mandal
Github: https://github.com/sujitmandal
Package   : https://pypi.org/project/images-into-array/
LinkedIn : https://www.linkedin.com/in/sujit-mandal-91215013a/
Facebook : https://www.facebook.com/sujit.mandal.33671748
Twitter : https://twitter.com/mandalsujit37
'''

def DNA(temp):

    st_temp = temp.replace('A', 't').replace('T', 'a').replace('C', 'g').replace('G', 'c').upper()[::-1]
    print(st_temp)

if __name__ == "__main__":
    DNA(string)
