s = 'CATACCAGAGCGTTGATACCAGATACCAGAATACCAGATGAATACCAGTATACCAGGGCATAACTCGCATACCAGGATACCAGGATACCAGATACCAGATGCGCGGGTATACCAGCATACCAGGGACGGATACCAGCGAGCGTATACCAGTAATACCAGTAGTATACCAGTTTACAAGATACCAGCAATACCAGTATACCAGTCATACCAGTTCTTCGGCGATACCAGCTGGAATACCAGAATACCAGGATACCAGAGATACCAGATACCAGTGATACCAGATACCAGACGAATACCAGTGATACCAGATACCAGAATACCAGAATACCAGACGAATACCAGGGATACCAGACTATACCAGATACCAGTTGATACCAGTAATACCAGGTAACGTATAATACCAGTTTATACCAGCATACCAGATACCAGATACCAGGTTAATACCAGCATACCAGTGACTAGGGATACCAGCATACCAGAACCACACATACCAGCCCGTATACCAGATACCAGATACCAGTATACCAGATACCAGCAATACCAGCACCTCCTTTTCAGTCTTCCAGCCGCCGGATACCAGGTACGATACCAGCATACCAGGCCTAATACCAGATACCAGTAATACCAGCATATGATACCAGATACCAGGTCTCTATTCATAATACCAGGCATACCAGTATACCAGCGGAACCAATACCAGGAAATACCAGCAATACCAGACAGATACCAGGTAGATACCAGGATACCAGAATACCAGAATACCAGAGGTATACCAGATACCAGAATACCAGACATACCAGATACCAGCATACCAGATACCAGGATACCAGATACCAGAAAATACCAGATAATACCAGACATACCAGATACCAGAATACCAGGAATACCAGATACCAGATACCAGATATACCAGTCGATACCAGTCGTATTGATACCAGATTCATACCAGGATACCAGCCATACCAGCATACCAG'
t = 'ATACCAGAT'

'''
Author : Sujit Mandal
Github: https://github.com/sujitmandal
Package   : https://pypi.org/project/images-into-array/
LinkedIn : https://www.linkedin.com/in/sujit-mandal-91215013a/
Facebook : https://www.facebook.com/sujit.mandal.33671748
Twitter : https://twitter.com/mandalsujit37
'''

def Motif_in_DNA(x,y):
    temp = []
    count = 1
    j = len(y)

    for i in range(len(x)):
        i = i + 1
        j = j + 1
        if x[i:j] == t:
            count = i + 1
            temp.append(count)

    print(*temp)


if __name__ == "__main__":
    Motif_in_DNA(s,t)